CREATE TABLE [dbo].[Purchases]
(
	[Id] NVARCHAR(50) NOT NULL PRIMARY KEY,
	[SellerId] NVARCHAR(50) NOT NULL,
	[BuyerId] NVARCHAR(50) NOT NULL,
	[PhoneId] NVARCHAR(50) NOT NULL,
	[PurchaseDate] DATETIME2(7) NOT NULL DEFAULT getutcdate()
)
