CREATE TABLE [dbo].[Table1]
(
	[Id] NVARCHAR(50) NOT NULL PRIMARY KEY,
	[Image] NVARCHAR(256) NOT NULL,
	[Email] NVARCHAR(150) NOT NULL,
	[UserName] NVARCHAR(150) NOT NULL,
	[Password] NVARCHAR(150) NOT NULL, 
	[Description] NVARCHAR(256) NULL, 
	[Phones_sold] int NOT NULL DEFAULT 0,
	[Contact] NVARCHAR(50) NULL,
)
